<?php

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
            array('id' => 1, 'sortname' => 'AF', 'name' => "Afghanistan", 'phonesortname' => 93),
            array('id' => 2, 'sortname' => 'AL', 'name' => "Albania", 'phonesortname' => 355),
            array('id' => 3, 'sortname' => 'DZ', 'name' => "Algeria", 'phonesortname' => 213),
            array('id' => 4, 'sortname' => 'AS', 'name' => "American Samoa", 'phonesortname' => 1684),
            array('id' => 5, 'sortname' => 'AD', 'name' => "Andorra", 'phonesortname' => 376),
            array('id' => 6, 'sortname' => 'AO', 'name' => "Angola", 'phonesortname' => 244),
            array('id' => 7, 'sortname' => 'AI', 'name' => "Anguilla", 'phonesortname' => 1264),
            array('id' => 8, 'sortname' => 'AQ', 'name' => "Antarctica", 'phonesortname' => 0),
            array('id' => 9, 'sortname' => 'AG', 'name' => "Antigua And Barbuda", 'phonesortname' => 1268),
            array('id' => 10, 'sortname' => 'AR', 'name' => "Argentina", 'phonesortname' => 54),
            array('id' => 11, 'sortname' => 'AM', 'name' => "Armenia", 'phonesortname' => 374),
            array('id' => 12, 'sortname' => 'AW', 'name' => "Aruba", 'phonesortname' => 297),
            array('id' => 13, 'sortname' => 'AU', 'name' => "Australia", 'phonesortname' => 61),
            array('id' => 14, 'sortname' => 'AT', 'name' => "Austria", 'phonesortname' => 43),
            array('id' => 15, 'sortname' => 'AZ', 'name' => "Azerbaijan", 'phonesortname' => 994),
            array('id' => 16, 'sortname' => 'BS', 'name' => "Bahamas The", 'phonesortname' => 1242),
            array('id' => 17, 'sortname' => 'BH', 'name' => "Bahrain", 'phonesortname' => 973),
            array('id' => 18, 'sortname' => 'BD', 'name' => "Bangladesh", 'phonesortname' => 880),
            array('id' => 19, 'sortname' => 'BB', 'name' => "Barbados", 'phonesortname' => 1246),
            array('id' => 20, 'sortname' => 'BY', 'name' => "Belarus", 'phonesortname' => 375),
            array('id' => 21, 'sortname' => 'BE', 'name' => "Belgium", 'phonesortname' => 32),
            array('id' => 22, 'sortname' => 'BZ', 'name' => "Belize", 'phonesortname' => 501),
            array('id' => 23, 'sortname' => 'BJ', 'name' => "Benin", 'phonesortname' => 229),
            array('id' => 24, 'sortname' => 'BM', 'name' => "Bermuda", 'phonesortname' => 1441),
            array('id' => 25, 'sortname' => 'BT', 'name' => "Bhutan", 'phonesortname' => 975),
            array('id' => 26, 'sortname' => 'BO', 'name' => "Bolivia", 'phonesortname' => 591),
            array('id' => 27, 'sortname' => 'BA', 'name' => "Bosnia and Herzegovina", 'phonesortname' => 387),
            array('id' => 28, 'sortname' => 'BW', 'name' => "Botswana", 'phonesortname' => 267),
            array('id' => 29, 'sortname' => 'BV', 'name' => "Bouvet Island", 'phonesortname' => 0),
            array('id' => 30, 'sortname' => 'BR', 'name' => "Brazil", 'phonesortname' => 55),
            array('id' => 31, 'sortname' => 'IO', 'name' => "British Indian Ocean Territory", 'phonesortname' => 246),
            array('id' => 32, 'sortname' => 'BN', 'name' => "Brunei", 'phonesortname' => 673),
            array('id' => 33, 'sortname' => 'BG', 'name' => "Bulgaria", 'phonesortname' => 359),
            array('id' => 34, 'sortname' => 'BF', 'name' => "Burkina Faso", 'phonesortname' => 226),
            array('id' => 35, 'sortname' => 'BI', 'name' => "Burundi", 'phonesortname' => 257),
            array('id' => 36, 'sortname' => 'KH', 'name' => "Cambodia", 'phonesortname' => 855),
            array('id' => 37, 'sortname' => 'CM', 'name' => "Cameroon", 'phonesortname' => 237),
            array('id' => 38, 'sortname' => 'CA', 'name' => "Canada", 'phonesortname' => 1),
            array('id' => 39, 'sortname' => 'CV', 'name' => "Cape Verde", 'phonesortname' => 238),
            array('id' => 40, 'sortname' => 'KY', 'name' => "Cayman Islands", 'phonesortname' => 1345),
            array('id' => 41, 'sortname' => 'CF', 'name' => "Central African Republic", 'phonesortname' => 236),
            array('id' => 42, 'sortname' => 'TD', 'name' => "Chad", 'phonesortname' => 235),
            array('id' => 43, 'sortname' => 'CL', 'name' => "Chile", 'phonesortname' => 56),
            array('id' => 44, 'sortname' => 'CN', 'name' => "China", 'phonesortname' => 86),
            array('id' => 45, 'sortname' => 'CX', 'name' => "Christmas Island", 'phonesortname' => 61),
            array('id' => 46, 'sortname' => 'CC', 'name' => "Cocos (Keeling) Islands", 'phonesortname' => 672),
            array('id' => 47, 'sortname' => 'CO', 'name' => "Colombia", 'phonesortname' => 57),
            array('id' => 48, 'sortname' => 'KM', 'name' => "Comoros", 'phonesortname' => 269),
            array('id' => 49, 'sortname' => 'CG', 'name' => "Congo", 'phonesortname' => 242),
            array('id' => 50, 'sortname' => 'CD', 'name' => "Congo The Democratic Republic Of The", 'phonesortname' => 242),
            array('id' => 51, 'sortname' => 'CK', 'name' => "Cook Islands", 'phonesortname' => 682),
            array('id' => 52, 'sortname' => 'CR', 'name' => "Costa Rica", 'phonesortname' => 506),
            array('id' => 53, 'sortname' => 'CI', 'name' => "Cote D Ivoire (Ivory Coast)", 'phonesortname' => 225),
            array('id' => 54, 'sortname' => 'HR', 'name' => "Croatia (Hrvatska)", 'phonesortname' => 385),
            array('id' => 55, 'sortname' => 'CU', 'name' => "Cuba", 'phonesortname' => 53),
            array('id' => 56, 'sortname' => 'CY', 'name' => "Cyprus", 'phonesortname' => 357),
            array('id' => 57, 'sortname' => 'CZ', 'name' => "Czech Republic", 'phonesortname' => 420),
            array('id' => 58, 'sortname' => 'DK', 'name' => "Denmark", 'phonesortname' => 45),
            array('id' => 59, 'sortname' => 'DJ', 'name' => "Djibouti", 'phonesortname' => 253),
            array('id' => 60, 'sortname' => 'DM', 'name' => "Dominica", 'phonesortname' => 1767),
            array('id' => 61, 'sortname' => 'DO', 'name' => "Dominican Republic", 'phonesortname' => 1809),
            array('id' => 62, 'sortname' => 'TP', 'name' => "East Timor", 'phonesortname' => 670),
            array('id' => 63, 'sortname' => 'EC', 'name' => "Ecuador", 'phonesortname' => 593),
            array('id' => 64, 'sortname' => 'EG', 'name' => "Egypt", 'phonesortname' => 20),
            array('id' => 65, 'sortname' => 'SV', 'name' => "El Salvador", 'phonesortname' => 503),
            array('id' => 66, 'sortname' => 'GQ', 'name' => "Equatorial Guinea", 'phonesortname' => 240),
            array('id' => 67, 'sortname' => 'ER', 'name' => "Eritrea", 'phonesortname' => 291),
            array('id' => 68, 'sortname' => 'EE', 'name' => "Estonia", 'phonesortname' => 372),
            array('id' => 69, 'sortname' => 'ET', 'name' => "Ethiopia", 'phonesortname' => 251),
            array('id' => 70, 'sortname' => 'XA', 'name' => "External Territories of Australia", 'phonesortname' => 61),
            array('id' => 71, 'sortname' => 'FK', 'name' => "Falkland Islands", 'phonesortname' => 500),
            array('id' => 72, 'sortname' => 'FO', 'name' => "Faroe Islands", 'phonesortname' => 298),
            array('id' => 73, 'sortname' => 'FJ', 'name' => "Fiji Islands", 'phonesortname' => 679),
            array('id' => 74, 'sortname' => 'FI', 'name' => "Finland", 'phonesortname' => 358),
            array('id' => 75, 'sortname' => 'FR', 'name' => "France", 'phonesortname' => 33),
            array('id' => 76, 'sortname' => 'GF', 'name' => "French Guiana", 'phonesortname' => 594),
            array('id' => 77, 'sortname' => 'PF', 'name' => "French Polynesia", 'phonesortname' => 689),
            array('id' => 78, 'sortname' => 'TF', 'name' => "French Southern Territories", 'phonesortname' => 0),
            array('id' => 79, 'sortname' => 'GA', 'name' => "Gabon", 'phonesortname' => 241),
            array('id' => 80, 'sortname' => 'GM', 'name' => "Gambia The", 'phonesortname' => 220),
            array('id' => 81, 'sortname' => 'GE', 'name' => "Georgia", 'phonesortname' => 995),
            array('id' => 82, 'sortname' => 'DE', 'name' => "Germany", 'phonesortname' => 49),
            array('id' => 83, 'sortname' => 'GH', 'name' => "Ghana", 'phonesortname' => 233),
            array('id' => 84, 'sortname' => 'GI', 'name' => "Gibraltar", 'phonesortname' => 350),
            array('id' => 85, 'sortname' => 'GR', 'name' => "Greece", 'phonesortname' => 30),
            array('id' => 86, 'sortname' => 'GL', 'name' => "Greenland", 'phonesortname' => 299),
            array('id' => 87, 'sortname' => 'GD', 'name' => "Grenada", 'phonesortname' => 1473),
            array('id' => 88, 'sortname' => 'GP', 'name' => "Guadeloupe", 'phonesortname' => 590),
            array('id' => 89, 'sortname' => 'GU', 'name' => "Guam", 'phonesortname' => 1671),
            array('id' => 90, 'sortname' => 'GT', 'name' => "Guatemala", 'phonesortname' => 502),
            array('id' => 91, 'sortname' => 'XU', 'name' => "Guernsey and Alderney", 'phonesortname' => 44),
            array('id' => 92, 'sortname' => 'GN', 'name' => "Guinea", 'phonesortname' => 224),
            array('id' => 93, 'sortname' => 'GW', 'name' => "Guinea-Bissau", 'phonesortname' => 245),
            array('id' => 94, 'sortname' => 'GY', 'name' => "Guyana", 'phonesortname' => 592),
            array('id' => 95, 'sortname' => 'HT', 'name' => "Haiti", 'phonesortname' => 509),
            array('id' => 96, 'sortname' => 'HM', 'name' => "Heard and McDonald Islands", 'phonesortname' => 0),
            array('id' => 97, 'sortname' => 'HN', 'name' => "Honduras", 'phonesortname' => 504),
            array('id' => 98, 'sortname' => 'HK', 'name' => "Hong Kong S.A.R.", 'phonesortname' => 852),
            array('id' => 99, 'sortname' => 'HU', 'name' => "Hungary", 'phonesortname' => 36),
            array('id' => 100, 'sortname' => 'IS', 'name' => "Iceland", 'phonesortname' => 354),
            array('id' => 101, 'sortname' => 'IN', 'name' => "India", 'phonesortname' => 91),
            array('id' => 102, 'sortname' => 'ID', 'name' => "Indonesia", 'phonesortname' => 62),
            array('id' => 103, 'sortname' => 'IR', 'name' => "Iran", 'phonesortname' => 98),
            array('id' => 104, 'sortname' => 'IQ', 'name' => "Iraq", 'phonesortname' => 964),
            array('id' => 105, 'sortname' => 'IE', 'name' => "Ireland", 'phonesortname' => 353),
            array('id' => 106, 'sortname' => 'IL', 'name' => "Israel", 'phonesortname' => 972),
            array('id' => 107, 'sortname' => 'IT', 'name' => "Italy", 'phonesortname' => 39),
            array('id' => 108, 'sortname' => 'JM', 'name' => "Jamaica", 'phonesortname' => 1876),
            array('id' => 109, 'sortname' => 'JP', 'name' => "Japan", 'phonesortname' => 81),
            array('id' => 110, 'sortname' => 'XJ', 'name' => "Jersey", 'phonesortname' => 44),
            array('id' => 111, 'sortname' => 'JO', 'name' => "Jordan", 'phonesortname' => 962),
            array('id' => 112, 'sortname' => 'KZ', 'name' => "Kazakhstan", 'phonesortname' => 7),
            array('id' => 113, 'sortname' => 'KE', 'name' => "Kenya", 'phonesortname' => 254),
            array('id' => 114, 'sortname' => 'KI', 'name' => "Kiribati", 'phonesortname' => 686),
            array('id' => 115, 'sortname' => 'KP', 'name' => "Korea North", 'phonesortname' => 850),
            array('id' => 116, 'sortname' => 'KR', 'name' => "Korea South", 'phonesortname' => 82),
            array('id' => 117, 'sortname' => 'KW', 'name' => "Kuwait", 'phonesortname' => 965),
            array('id' => 118, 'sortname' => 'KG', 'name' => "Kyrgyzstan", 'phonesortname' => 996),
            array('id' => 119, 'sortname' => 'LA', 'name' => "Laos", 'phonesortname' => 856),
            array('id' => 120, 'sortname' => 'LV', 'name' => "Latvia", 'phonesortname' => 371),
            array('id' => 121, 'sortname' => 'LB', 'name' => "Lebanon", 'phonesortname' => 961),
            array('id' => 122, 'sortname' => 'LS', 'name' => "Lesotho", 'phonesortname' => 266),
            array('id' => 123, 'sortname' => 'LR', 'name' => "Liberia", 'phonesortname' => 231),
            array('id' => 124, 'sortname' => 'LY', 'name' => "Libya", 'phonesortname' => 218),
            array('id' => 125, 'sortname' => 'LI', 'name' => "Liechtenstein", 'phonesortname' => 423),
            array('id' => 126, 'sortname' => 'LT', 'name' => "Lithuania", 'phonesortname' => 370),
            array('id' => 127, 'sortname' => 'LU', 'name' => "Luxembourg", 'phonesortname' => 352),
            array('id' => 128, 'sortname' => 'MO', 'name' => "Macau S.A.R.", 'phonesortname' => 853),
            array('id' => 129, 'sortname' => 'MK', 'name' => "Macedonia", 'phonesortname' => 389),
            array('id' => 130, 'sortname' => 'MG', 'name' => "Madagascar", 'phonesortname' => 261),
            array('id' => 131, 'sortname' => 'MW', 'name' => "Malawi", 'phonesortname' => 265),
            array('id' => 132, 'sortname' => 'MY', 'name' => "Malaysia", 'phonesortname' => 60),
            array('id' => 133, 'sortname' => 'MV', 'name' => "Maldives", 'phonesortname' => 960),
            array('id' => 134, 'sortname' => 'ML', 'name' => "Mali", 'phonesortname' => 223),
            array('id' => 135, 'sortname' => 'MT', 'name' => "Malta", 'phonesortname' => 356),
            array('id' => 136, 'sortname' => 'XM', 'name' => "Man (Isle of)", 'phonesortname' => 44),
            array('id' => 137, 'sortname' => 'MH', 'name' => "Marshall Islands", 'phonesortname' => 692),
            array('id' => 138, 'sortname' => 'MQ', 'name' => "Martinique", 'phonesortname' => 596),
            array('id' => 139, 'sortname' => 'MR', 'name' => "Mauritania", 'phonesortname' => 222),
            array('id' => 140, 'sortname' => 'MU', 'name' => "Mauritius", 'phonesortname' => 230),
            array('id' => 141, 'sortname' => 'YT', 'name' => "Mayotte", 'phonesortname' => 269),
            array('id' => 142, 'sortname' => 'MX', 'name' => "Mexico", 'phonesortname' => 52),
            array('id' => 143, 'sortname' => 'FM', 'name' => "Micronesia", 'phonesortname' => 691),
            array('id' => 144, 'sortname' => 'MD', 'name' => "Moldova", 'phonesortname' => 373),
            array('id' => 145, 'sortname' => 'MC', 'name' => "Monaco", 'phonesortname' => 377),
            array('id' => 146, 'sortname' => 'MN', 'name' => "Mongolia", 'phonesortname' => 976),
            array('id' => 147, 'sortname' => 'MS', 'name' => "Montserrat", 'phonesortname' => 1664),
            array('id' => 148, 'sortname' => 'MA', 'name' => "Morocco", 'phonesortname' => 212),
            array('id' => 149, 'sortname' => 'MZ', 'name' => "Mozambique", 'phonesortname' => 258),
            array('id' => 150, 'sortname' => 'MM', 'name' => "Myanmar", 'phonesortname' => 95),
            array('id' => 151, 'sortname' => 'NA', 'name' => "Namibia", 'phonesortname' => 264),
            array('id' => 152, 'sortname' => 'NR', 'name' => "Nauru", 'phonesortname' => 674),
            array('id' => 153, 'sortname' => 'NP', 'name' => "Nepal", 'phonesortname' => 977),
            array('id' => 154, 'sortname' => 'AN', 'name' => "Netherlands Antilles", 'phonesortname' => 599),
            array('id' => 155, 'sortname' => 'NL', 'name' => "Netherlands The", 'phonesortname' => 31),
            array('id' => 156, 'sortname' => 'NC', 'name' => "New Caledonia", 'phonesortname' => 687),
            array('id' => 157, 'sortname' => 'NZ', 'name' => "New Zealand", 'phonesortname' => 64),
            array('id' => 158, 'sortname' => 'NI', 'name' => "Nicaragua", 'phonesortname' => 505),
            array('id' => 159, 'sortname' => 'NE', 'name' => "Niger", 'phonesortname' => 227),
            array('id' => 160, 'sortname' => 'NG', 'name' => "Nigeria", 'phonesortname' => 234),
            array('id' => 161, 'sortname' => 'NU', 'name' => "Niue", 'phonesortname' => 683),
            array('id' => 162, 'sortname' => 'NF', 'name' => "Norfolk Island", 'phonesortname' => 672),
            array('id' => 163, 'sortname' => 'MP', 'name' => "Northern Mariana Islands", 'phonesortname' => 1670),
            array('id' => 164, 'sortname' => 'NO', 'name' => "Norway", 'phonesortname' => 47),
            array('id' => 165, 'sortname' => 'OM', 'name' => "Oman", 'phonesortname' => 968),
            array('id' => 166, 'sortname' => 'PK', 'name' => "Pakistan", 'phonesortname' => 92),
            array('id' => 167, 'sortname' => 'PW', 'name' => "Palau", 'phonesortname' => 680),
            array('id' => 168, 'sortname' => 'PS', 'name' => "Palestinian Territory Occupied", 'phonesortname' => 970),
            array('id' => 169, 'sortname' => 'PA', 'name' => "Panama", 'phonesortname' => 507),
            array('id' => 170, 'sortname' => 'PG', 'name' => "Papua new Guinea", 'phonesortname' => 675),
            array('id' => 171, 'sortname' => 'PY', 'name' => "Paraguay", 'phonesortname' => 595),
            array('id' => 172, 'sortname' => 'PE', 'name' => "Peru", 'phonesortname' => 51),
            array('id' => 173, 'sortname' => 'PH', 'name' => "Philippines", 'phonesortname' => 63),
            array('id' => 174, 'sortname' => 'PN', 'name' => "Pitcairn Island", 'phonesortname' => 0),
            array('id' => 175, 'sortname' => 'PL', 'name' => "Poland", 'phonesortname' => 48),
            array('id' => 176, 'sortname' => 'PT', 'name' => "Portugal", 'phonesortname' => 351),
            array('id' => 177, 'sortname' => 'PR', 'name' => "Puerto Rico", 'phonesortname' => 1787),
            array('id' => 178, 'sortname' => 'QA', 'name' => "Qatar", 'phonesortname' => 974),
            array('id' => 179, 'sortname' => 'RE', 'name' => "Reunion", 'phonesortname' => 262),
            array('id' => 180, 'sortname' => 'RO', 'name' => "Romania", 'phonesortname' => 40),
            array('id' => 181, 'sortname' => 'RU', 'name' => "Russia", 'phonesortname' => 70),
            array('id' => 182, 'sortname' => 'RW', 'name' => "Rwanda", 'phonesortname' => 250),
            array('id' => 183, 'sortname' => 'SH', 'name' => "Saint Helena", 'phonesortname' => 290),
            array('id' => 184, 'sortname' => 'KN', 'name' => "Saint Kitts And Nevis", 'phonesortname' => 1869),
            array('id' => 185, 'sortname' => 'LC', 'name' => "Saint Lucia", 'phonesortname' => 1758),
            array('id' => 186, 'sortname' => 'PM', 'name' => "Saint Pierre and Miquelon", 'phonesortname' => 508),
            array('id' => 187, 'sortname' => 'VC', 'name' => "Saint Vincent And The Grenadines", 'phonesortname' => 1784),
            array('id' => 188, 'sortname' => 'WS', 'name' => "Samoa", 'phonesortname' => 684),
            array('id' => 189, 'sortname' => 'SM', 'name' => "San Marino", 'phonesortname' => 378),
            array('id' => 190, 'sortname' => 'ST', 'name' => "Sao Tome and Principe", 'phonesortname' => 239),
            array('id' => 191, 'sortname' => 'SA', 'name' => "Saudi Arabia", 'phonesortname' => 966),
            array('id' => 192, 'sortname' => 'SN', 'name' => "Senegal", 'phonesortname' => 221),
            array('id' => 193, 'sortname' => 'RS', 'name' => "Serbia", 'phonesortname' => 381),
            array('id' => 194, 'sortname' => 'SC', 'name' => "Seychelles", 'phonesortname' => 248),
            array('id' => 195, 'sortname' => 'SL', 'name' => "Sierra Leone", 'phonesortname' => 232),
            array('id' => 196, 'sortname' => 'SG', 'name' => "Singapore", 'phonesortname' => 65),
            array('id' => 197, 'sortname' => 'SK', 'name' => "Slovakia", 'phonesortname' => 421),
            array('id' => 198, 'sortname' => 'SI', 'name' => "Slovenia", 'phonesortname' => 386),
            array('id' => 199, 'sortname' => 'XG', 'name' => "Smaller Territories of the UK", 'phonesortname' => 44),
            array('id' => 200, 'sortname' => 'SB', 'name' => "Solomon Islands", 'phonesortname' => 677),
            array('id' => 201, 'sortname' => 'SO', 'name' => "Somalia", 'phonesortname' => 252),
            array('id' => 202, 'sortname' => 'ZA', 'name' => "South Africa", 'phonesortname' => 27),
            array('id' => 203, 'sortname' => 'GS', 'name' => "South Georgia", 'phonesortname' => 0),
            array('id' => 204, 'sortname' => 'SS', 'name' => "South Sudan", 'phonesortname' => 211),
            array('id' => 205, 'sortname' => 'ES', 'name' => "Spain", 'phonesortname' => 34),
            array('id' => 206, 'sortname' => 'LK', 'name' => "Sri Lanka", 'phonesortname' => 94),
            array('id' => 207, 'sortname' => 'SD', 'name' => "Sudan", 'phonesortname' => 249),
            array('id' => 208, 'sortname' => 'SR', 'name' => "Suriname", 'phonesortname' => 597),
            array('id' => 209, 'sortname' => 'SJ', 'name' => "Svalbard And Jan Mayen Islands", 'phonesortname' => 47),
            array('id' => 210, 'sortname' => 'SZ', 'name' => "Swaziland", 'phonesortname' => 268),
            array('id' => 211, 'sortname' => 'SE', 'name' => "Sweden", 'phonesortname' => 46),
            array('id' => 212, 'sortname' => 'CH', 'name' => "Switzerland", 'phonesortname' => 41),
            array('id' => 213, 'sortname' => 'SY', 'name' => "Syria", 'phonesortname' => 963),
            array('id' => 214, 'sortname' => 'TW', 'name' => "Taiwan", 'phonesortname' => 886),
            array('id' => 215, 'sortname' => 'TJ', 'name' => "Tajikistan", 'phonesortname' => 992),
            array('id' => 216, 'sortname' => 'TZ', 'name' => "Tanzania", 'phonesortname' => 255),
            array('id' => 217, 'sortname' => 'TH', 'name' => "Thailand", 'phonesortname' => 66),
            array('id' => 218, 'sortname' => 'TG', 'name' => "Togo", 'phonesortname' => 228),
            array('id' => 219, 'sortname' => 'TK', 'name' => "Tokelau", 'phonesortname' => 690),
            array('id' => 220, 'sortname' => 'TO', 'name' => "Tonga", 'phonesortname' => 676),
            array('id' => 221, 'sortname' => 'TT', 'name' => "Trinidad And Tobago", 'phonesortname' => 1868),
            array('id' => 222, 'sortname' => 'TN', 'name' => "Tunisia", 'phonesortname' => 216),
            array('id' => 223, 'sortname' => 'TR', 'name' => "Turkey", 'phonesortname' => 90),
            array('id' => 224, 'sortname' => 'TM', 'name' => "Turkmenistan", 'phonesortname' => 7370),
            array('id' => 225, 'sortname' => 'TC', 'name' => "Turks And Caicos Islands", 'phonesortname' => 1649),
            array('id' => 226, 'sortname' => 'TV', 'name' => "Tuvalu", 'phonesortname' => 688),
            array('id' => 227, 'sortname' => 'UG', 'name' => "Uganda", 'phonesortname' => 256),
            array('id' => 228, 'sortname' => 'UA', 'name' => "Ukraine", 'phonesortname' => 380),
            array('id' => 229, 'sortname' => 'AE', 'name' => "United Arab Emirates", 'phonesortname' => 971),
            array('id' => 230, 'sortname' => 'GB', 'name' => "United Kingdom", 'phonesortname' => 44),
            array('id' => 231, 'sortname' => 'US', 'name' => "United States", 'phonesortname' => 1),
            array('id' => 232, 'sortname' => 'UM', 'name' => "United States Minor Outlying Islands", 'phonesortname' => 1),
            array('id' => 233, 'sortname' => 'UY', 'name' => "Uruguay", 'phonesortname' => 598),
            array('id' => 234, 'sortname' => 'UZ', 'name' => "Uzbekistan", 'phonesortname' => 998),
            array('id' => 235, 'sortname' => 'VU', 'name' => "Vanuatu", 'phonesortname' => 678),
            array('id' => 236, 'sortname' => 'VA', 'name' => "Vatican City State (Holy See)", 'phonesortname' => 39),
            array('id' => 237, 'sortname' => 'VE', 'name' => "Venezuela", 'phonesortname' => 58),
            array('id' => 238, 'sortname' => 'VN', 'name' => "Vietnam", 'phonesortname' => 84),
            array('id' => 239, 'sortname' => 'VG', 'name' => "Virgin Islands (British)", 'phonesortname' => 1284),
            array('id' => 240, 'sortname' => 'VI', 'name' => "Virgin Islands (US)", 'phonesortname' => 1340),
            array('id' => 241, 'sortname' => 'WF', 'name' => "Wallis And Futuna Islands", 'phonesortname' => 681),
            array('id' => 242, 'sortname' => 'EH', 'name' => "Western Sahara", 'phonesortname' => 212),
            array('id' => 243, 'sortname' => 'YE', 'name' => "Yemen", 'phonesortname' => 967),
            array('id' => 244, 'sortname' => 'YU', 'name' => "Yugoslavia", 'phonesortname' => 38),
            array('id' => 245, 'sortname' => 'ZM', 'name' => "Zambia", 'phonesortname' => 260),
            array('id' => 246, 'sortname' => 'ZW', 'name' => "Zimbabwe", 'phonesortname' => 263),
        );
        DB::table('countries')->insert($countries);
    }
}
